name: Documentation

on:
    push:
        branches: [ "main" ]
    workflow_dispatch:

permissions:
    contents: read
    pages: write
    id-token: write

concurrency:
    group: "pages"
    cancel-in-progress: false

jobs:
    build-and-deploy:
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        timeout-minutes: 15
        steps:
            -   name: Checkout
                uses: actions/checkout@v6
                with:
                    fetch-depth: 1

            -   name: Prepare Java
                uses: actions/setup-java@v5
                with:
                    distribution: "oracle"
                    java-version: "26"

            -   name: Install Clojure tools
                uses: DeLaGuardo/setup-clojure@02f5a82b79a547523e664fe8a7a32ea14884d7b2 # 13.6.0
                with:
                    cli: latest

            -   name: Cache Clojure dependencies
                uses: actions/cache@v5
                with:
                    path: |
                        ~/.m2/repository
                        ~/.gitlibs
                        ~/.deps.clj
                    key: ${{ runner.os }}-cljdeps-${{ hashFiles('deps.edn') }}
                    restore-keys: ${{ runner.os }}-cljdeps-

            -   name: Generate API documentation
                run: clojure -T:build docs

            -   name: Setup GitHub Pages
                uses: actions/configure-pages@v6.0.0

            -   name: Upload artifact
                uses: actions/upload-pages-artifact@v5
                with:
                    path: "target/docs"

            -   name: Deploy to GitHub Pages
                id: deployment
                uses: actions/deploy-pages@v5
