name: Release to Clojars

on:
    push:
        tags:
            - 'v*'

permissions:
    contents: read

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: false

jobs:
    release:
        runs-on: ubuntu-latest
        timeout-minutes: 20
        environment: release
        steps:
            -   name: Checkout
                uses: actions/checkout@v6
                with:
                    fetch-depth: 1

            -   name: Prepare Java
                uses: actions/setup-java@v5
                with:
                    distribution: "oracle"
                    java-version: "26"

            -   name: Install Clojure tools
                uses: DeLaGuardo/setup-clojure@02f5a82b79a547523e664fe8a7a32ea14884d7b2 # 13.6.0
                with:
                    cli: latest

            -   name: Cache Clojure dependencies
                uses: actions/cache@v5
                with:
                    path: |
                        ~/.m2/repository
                        ~/.gitlibs
                        ~/.deps.clj
                    key: ${{ runner.os }}-cljdeps-${{ hashFiles('deps.edn') }}
                    restore-keys: ${{ runner.os }}-cljdeps-

            -   name: Build and deploy
                env:
                    CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
                    CLOJARS_PASSWORD: ${{ secrets.CLOJARS_DEPLOY_TOKEN }}
                run: |
                    clojure -T:build build-jar :release true
                    clojure -T:build deploy :release true
